baseURL = ''
relativeURLs = true
languageCode = 'en'
title = 'Rhea Myers'

staticDir = "assets"

#theme = "hugo-bootstrap-5"
#disableKinds = ["contact", "post", "section", "taxonomy"]
#ignoreErrors = ["error-disable-taxonomy"]

[params]
  copyright ="Copyright © 2023 Myers Studio Ltd."
  subtitle = "Doubling down on blockchain art"
  #mainSections = ["post","posts"]
  #logo = "img/avatar-icon.png" # Expecting square dimensions
  #favicon = "img/favicon.ico"
  dateFormat = "2022-01-01"
  commit = false
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  showRelatedPosts = false

[permalinks]
  # Allow source to be origanized but all pages to be top-level
  # Be careful to avoid name collisions.
  art = '/:filename/'
  writing = '/:filename/'
  information = '/:filename/'
  shows = '/:filename/'
  press = '/:filename/'

[[menu.main]]
    name = "Art"
    url = "/art/index.html"
    weight = 10

[[menu.main]]
    name = "Shows"
    url = "/shows/index.html"
    weight = 12

[[menu.main]]
    name = "Affiliations"
    url = "/affiliations/index.html"
    weight = 14

[[menu.main]]
    name = "Press"
    url = "/press/index.html"
    weight = 16

[[menu.main]]
    name = "Writing"
    url = "/writing/index.html"
    weight = 20

[[menu.main]]
    name = "Code"
    url = "https://git.rhea.art/"
    weight = 30

#[[menu.main]]
#    name = "Information"
#    url = "/information/index.html"
#    weight = 40
