baseURL = ''
relativeURLs = true
languageCode = 'en'
title = 'Rhea Myers'

staticDir = "assets"

#theme = "hugo-bootstrap-5"
#disableKinds = ["contact", "post", "section", "taxonomy"]
#ignoreErrors = ["error-disable-taxonomy"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
    [markup.goldmark.renderer]
      # Allow raw html in markdown
      unsafe = true

[params]
  copyright = "Copyright © 2025 Myers Studio Ltd."
  subtitle = "Making NFTs into art"
  #mainSections = ["post","posts"]
  #logo = "img/avatar-icon.png" # Expecting square dimensions
  #favicon = "img/favicon.ico"
  dateFormat = "2022-01-01"
  commit = false
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  showRelatedPosts = false

[permalinks]
  # Allow source to be origanized but all pages to be top-level
  # Be careful to avoid name collisions.
  art = '/:filename/'
  writing = '/:filename/'
  about = '/:filename/'
  shows = '/:filename/'
  press = '/:filename/'
  blog = '/:year/:month/:day/:slug/'

[[menu.main]]
    name = "Art"
    url = "/art/"
    weight = 10

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 16

# [[menu.main]]
#     name = "Writing"
#     url = "/writing/"
#     weight = 20

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30

#[[menu.main]]
#    name = "Information"
#    url = "/information/index.html"
#    weight = 40
